# Generated by Django 4.0.6 on 2022-08-21 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'descriptor',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_filepath', models.FileField(default='Not Avaliable', upload_to=exp.models.experiment_data_filepath, verbose_name='Metadata file')),
                ('data_filepath', models.FileField(default='Not Avaliable', upload_to=exp.models.experiment_data_filepath, verbose_name='Results file')),
            ],
        ),
        migrations.CreateModel(
            name='ExpPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('n_reads', models.IntegerField()),
                ('length_libtype', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ModelOrganism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('human', 'Human'), ('bacteria', 'Bacteria'), ('mouse', 'Mouse'), ('c.elegans', 'Caenorhabditis elegans')], max_length=200, verbose_name='Organism type')),
            ],
        ),
        migrations.CreateModel(
            name='PrepMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='', max_length=150)),
                ('kit', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_value', models.CharField(max_length=100, verbose_name='Sample ID')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.experiment')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='organism',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exp.modelorganism', verbose_name='Model Organism'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exp.expplatform', verbose_name='Experiment Platform'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='prep_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exp.prepmethod', verbose_name='Preparation Method'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exp.project', verbose_name='Experiment Project'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.CreateModel(
            name='DescriptorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.descriptor')),
            ],
            options={
                'unique_together': {('descriptor', 'value')},
            },
        ),
        migrations.CreateModel(
            name='DescriptorMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('desc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.descriptor', verbose_name='Descriptor')),
                ('desc_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.descriptorvalue', verbose_name='Descriptor Value')),
            ],
            options={
                'unique_together': {('desc_value', 'desc_name', 'content_type', 'object_id')},
            },
        ),
    ]
