# Generated by Django 4.0.4 on 2022-09-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handleddirectory',
            name='directory_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Experiment Directory'),
        ),
    ]
