# Generated by Django 4.0.4 on 2022-06-20 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('exp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'organism',
            },
        ),
        migrations.AddField(
            model_name='modelorganism',
            name='name',
            field=models.CharField(default='Default Organism', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrganismValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.organism')),
            ],
            options={
                'unique_together': {('organism', 'value')},
            },
        ),
        migrations.CreateModel(
            name='OrganismMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='model organism')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.organism')),
                ('organism_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.organismvalue')),
            ],
        ),
    ]
