# Generated by Django 4.0.4 on 2022-06-22 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('exp', '0002_organism_modelorganism_name_organismvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'descriptor',
            },
        ),
        migrations.CreateModel(
            name='DescriptorMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='museum item')),
                ('desc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.descriptor')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.descriptor')),
            ],
            options={
                'unique_together': {('descriptor', 'value')},
            },
        ),
        migrations.RemoveField(
            model_name='organismmap',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='organismmap',
            name='organism',
        ),
        migrations.RemoveField(
            model_name='organismmap',
            name='organism_value',
        ),
        migrations.AlterUniqueTogether(
            name='organismvalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='organismvalue',
            name='organism',
        ),
        migrations.DeleteModel(
            name='Organism',
        ),
        migrations.DeleteModel(
            name='OrganismMap',
        ),
        migrations.DeleteModel(
            name='OrganismValue',
        ),
        migrations.AddField(
            model_name='descriptormap',
            name='desc_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.descriptorvalue'),
        ),
        migrations.AlterUniqueTogether(
            name='descriptormap',
            unique_together={('desc_value', 'desc_name', 'content_type', 'object_id')},
        ),
    ]
