# Generated by Django 4.0.4 on 2022-06-24 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('exp', '0003_descriptor_descriptormap_descriptorvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='descriptormap',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='model'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='conditions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exp.expconditions'),
        ),
    ]
