# Generated by Django 4.1 on 2022-09-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0003_alter_handledurl_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandledDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_name', models.CharField(max_length=200, verbose_name='Experiment Directory')),
            ],
        ),
        migrations.DeleteModel(
            name='HandledURL',
        ),
        migrations.AlterUniqueTogether(
            name='descriptorvalue',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AlterField(
            model_name='descriptorvalue',
            name='value',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='prepmethod',
            unique_together={('method', 'kit')},
        ),
    ]
