# Generated by Django 4.0.4 on 2022-07-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0005_experiment_metadata_filepath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelorganism',
            name='name',
            field=models.CharField(choices=[('human', 'human'), ('bacteria', 'bacteria'), ('mouse', 'mouse'), ('c.elegans', 'c.elegans')], max_length=200, verbose_name='Organism type'),
        ),
    ]
