# Generated by Django 4.0.4 on 2022-07-30 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('exp', '0006_alter_modelorganism_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptormap',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Django Model'),
        ),
    ]
