# Generated by Django 4.0.6 on 2022-08-12 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('exp', '0009_remove_experiment_conditions_delete_expconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptormap',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='descriptormap',
            name='desc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.descriptor', verbose_name='Descriptor'),
        ),
        migrations.AlterField(
            model_name='descriptormap',
            name='desc_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.descriptorvalue', verbose_name='Descriptor Value'),
        ),
    ]
